version: "2.1"
services:
  vscode:
#    image: ghcr.io/linuxserver/code-server
    image: linuxserver/code-server
    container_name: vscode-server
    dns:
      - 172.17.0.1
#      - 192.168.1.30
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
#      - ./workspace:/config/workspace
      - ..:/config/workspace
      - ./ssh:/config/.ssh
#    expose:
#      - 6043
    ports:
      - 6043:8443
#      - 127.0.0.1:6043:8443
    restart: unless-stopped
    network_mode: bridge
#    network_mode: host
#    networks:
#      - vscode-host-network
#      - vscode-bridge-network

# networks:
#   vscode-host-network:
#     driver: host
#   vscode-bridge-network:
#     driver: bridge

# docker-compose up -d

# https://hub.docker.com/r/linuxserver/code-server
# https://packetriot.com/tutorials/posts/self-host-vs-code-server/

# docker exec -it --user root vscode-server /bin/sh

# ssh key
# ssh-keygen -q -N '' -b 4096 -f
# ssh -Tvvv gitea.lan
# cat /etc/resolv.conf

# sudo netstat -tulpn
# netstat -nr
# sudo iptables -L -t nat -n
# docker inspect vscode-server | less